// <auto-generated />
namespace RestaurantlyMVCProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addNotificationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNotificationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202502201207375_addNotificationTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
